version: '3'

services:
  snipeit:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: snipeit
    ports:
    - "8080:80"
    volumes:
    - logs:/var/www/html/storage/logs
#mount html folder to workspcace with read write access
    - ./:/var/www/html/:rw
    depends_on:
    - snipe-mariadb
    - snipe-redis
    env_file:
    - .env.docker
    networks:
    - snipeit-backend

  snipe-mariadb:
    image: mariadb:latest
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.docker
    networks:
    - snipeit-backend
    ports:
    - "3306:3306"

  snipe-redis:
    image: redis:6.2.5-buster
    networks:
    - snipeit-backend

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
    # - 1025:1025
    - "8025:8025"
    networks:
    - snipeit-backend


volumes:
  db: {}
  logs: {}

networks:
  snipeit-backend: {}
